import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider publishableKey="pk_test_a25vd24tc3dhbi02Mi5jbGVyay5hY2NvdW50cy5kZXYk">
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} bg-[#f1f1f1] antialiased`}
        >
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
